# Website information
title: Act Without Expectation
tagline: AWE and inspire
author: Noah Pierau
description: AWE is the personal website of Noah Pierau
baseurl: "" # the subpath of your site, e.g. /blog
url: http://localhost:4000 # change back to "" // the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: noahpierau

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
  
exclude:
  - Gemfile
  - Gemfile.lock
