# Website information
title: Act Without Expectation
author: Noah Pierau
description: > # this means to ignore newlines until "baseurl:"
  Welcome! Feel at home
baseurl: "" # the subpath of your site, e.g. /blog
url: http://localhost:4000 # change back to "" // the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
  
exclude:
  - Gemfile
  - Gemfile.lock
