# Website information
title: AWE
tagline: Act Without Expectation
author: Noah Pierau
description: AWE is the personal homepage of Noah Pierau.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://localhost:4000 # change back to "" // the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: noahpierau

# Build settings
markdown: kramdown
theme: minima
  
exclude:
  - Gemfile
  - Gemfile.lock
